### ISSUE TITLE
Update gradmap files to include filters and re-usable gradient maps

### ISSUE THREAD

**Issue by adam-coster** [bscotch/spritely#19]
Our current workflow from Clip Studio Paint has *all* images used to create a character or other animated asset exported into a flat-heirarchy output folder. We then have gradient maps that need to be applied to arbitrary subsets of those images.

For example, we may have files:

+ `arm.png`
+ `leg.png`
+ `eyes.png`
+ `faceplate.png`
+ `effect_slash.png`

Where the arm and leg need one set of gradmaps, the eyes don't use a gradmap at all, and the faceplate and effects share some gradmaps, and the effects also have their own.

Being able to mix-and-match gradmaps using pattern filters would help quite a bit.

The current `gradmap` file structure is:

```yml
## General structure
# [gradmap-name]:
#   [position]: [hex-color]

## Example
spooky:
  0: "000000"
  100: "ffffff"
```

It should be changed to the following to allow for re-usable gradmaps.

```yml
# "Skins" are the gradient mappings. Each one ends up being a folder
# into which mapped images are placed. There is an implicit "default"
# skin that doesn't do anything.
skins:
  flux:
    0: "000000"
    100: "ffffff"
  spooky:
    0: "ff0000"
    0: "ff00ff"

# "Groups" are collections of images to which skins are applied.
# If no groups are provided, all skins are assumed to apply to all images.
# If *any* groups are provided, images will only be skinned if they match a group.
# Matching patterns are regex, and must be directly usable by JavaScript's `new RegExp()` method.
# Case is always ignored. An image could land in multiple groups, and in that case
# will be skinned with the skins from all matching groups. Groups have no impact on
# output location or filename. Images that land in no groups are copied into the "default"
# skin folder, without being changed.
groups:
  - pattern: "^faceplate_" # Matches all image names starting with `faceplate_`
    skins:
      - flux
      - spooky
  - pattern: "^(?!eyes_)" # Matches anything that *doesn't* start with `eyes_` (using negative lookahead)
    skins:
      - spooky
```
